FROM python:3.11-slim

WORKDIR /app


COPY backend/requirements.txt app/backend/requirements.txt
RUN pip install --no-cache-dir -r app/backend/requirements.txt gunicorn python-dotenv



COPY backend app/backend


COPY frontend/templates app/backend/templates
COPY frontend/static app/backend/static

ENV PYTHONPATH=/app \
    PYTHONUNBUFFERED=1 \
    FLASK_SECRET_KEY=dev-secret-change-me

EXPOSE 8000

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "--workers", "3", "--preload", "app.backend.server:app"]