FROM python:3.11-slim

WORKDIR /app


COPY backend/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt gunicorn python-dotenv



COPY backend/ .

COPY frontend/templates templates/
COPY frontend/static static/

ENV PYTHONPATH=/app \
    PYTHONUNBUFFERED=1 \
    FLASK_SECRET_KEY=dev-secret-change-me

EXPOSE 8000

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "--workers", "3", "--preload", "server:app"]